version: "3.9"

services:
  backend:
    restart: always
    build:
      context: .
    # ports:
    #   - "3000:3000"
    #   - "9229:9229"
    command: tail -f /dev/null
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - ./.aws:/home/node/.aws
    working_dir: /app

